<?xml version='1.0'?>

<robot name="my_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find my_robot)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find my_robot)/urdf/my_robot.gazebo"/>
  
  <xacro:property name="chassis_length" value="0.4"/>
  <xacro:property name="chassis_width" value="0.2"/>
  <xacro:property name="chassis_height" value="0.1"/>
  
  <xacro:property name="wheel_radius" value="0.1"/>git 
  <xacro:property name="wheel_length" value="0.05"/>
  
  <link name="robot_footprint"></link>
  
  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>

  <link name='chassis'>
    <pose>0 0 0.1 0 0 0</pose>
    <inertial>
      <mass value="15.0"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy=" 0 0 0"/> 
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <xacro:material_blue/>
    </visual>
  </link>
  
  
  <joint name="chassis_joint_1" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="chassis"/>
    <child link="caster" />
  </joint>
  
  
  <link name="caster">
    <!-- pose>-0.15 0 -0.05 0 0 0</pose -->
    <collision>
      <origin xyz="-0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="-0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <xacro:material_blue/>
    </visual> 
  </link>
  
  
  <joint name="left_wheel_hinge" type="continuous">
    <origin xyz="${chassis_length/2-wheel_radius} ${(chassis_width/2+wheel_length/2+0.005)*(1)} 0" rpy="0 0 0" />
    <parent link="chassis"/>
    <child link="wheel_left"/>
    <axis xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>
  
  <link name="wheel_left">
    <inertial>
      <mass value="5.0"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 1.5708 1.5708"/>
      <!--origin xyz="${chassis_length/2-wheel_radius} ${(chassis_width/2+wheel_length/2+0.005)*(-1)} 0" rpy=" 0 1.5708 1.5708"/ -->
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 1.5708 1.5708"/>
      <!-- origin xyz="${chassis_length/2-wheel_radius} ${(chassis_width/2+wheel_length/2+0.005)*(-1)} 0" rpy=" 0 1.5708 1.5708"/ -->
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <xacro:material_dark_grey/>
    </visual> 
  </link>
  
  
  <joint name="right_wheel_hinge" type="continuous">
    <origin xyz="${chassis_length/2-wheel_radius} ${(chassis_width/2+wheel_length/2+0.005)*(-1)} 0" rpy="0 0 0" />
    <parent link="chassis"/>
    <child link="wheel_right"/>
    <axis xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>
  
  <link name="wheel_right">
    <inertial>
      <mass value="5.0"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 1.5708 1.5708"/>
      <!-- origin xyz="${chassis_length/2-wheel_radius} ${(chassis_width/2+wheel_length/2+0.005)*(1)} 0" rpy=" 0 1.5708 1.5708"/ -->
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 1.5708 1.5708"/>
      <!-- origin xyz="${chassis_length/2-wheel_radius} ${(chassis_width/2+wheel_length/2+0.005)*(1)} 0" rpy=" 0 1.5708 1.5708"/ -->
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <xacro:material_dark_grey/>
    </visual> 
  </link>


  <!-- Add sensors -->
  
  <link name="camera">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <xacro:material_red/>
    </visual> 
  </link>
  
  <joint name="camera_joint" type="fixed">
    <origin xyz="${chassis_length/2} 0 0" rpy="0 0 0" />
    <parent link="chassis"/>
    <child link="camera"/>
  </joint>
  
  
  <link name="hokuyo">
    <inertial>
      <mass value="1e-5"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://my_robot/meshes/hokuyo.dae"/>
      </geometry>
    </visual> 
  </link>
  
  <joint name="hokuyo_joint" type="fixed">
    <origin xyz="0.15 0 0.1" rpy="0 0 0" />
    <parent link="chassis"/>
    <child link="hokuyo"/>
  </joint>

</robot>

